# Generated by Django 5.0.6 on 2024-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.IntegerField(help_text='Enter valid year format (e.g. 1999, 2021, etc.)', unique=True),
        ),
    ]
