# Generated by Django 5.0.6 on 2024-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_photo_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='day',
            field=models.DateField(),
        ),
    ]
