# Generated by Django 5.0.6 on 2024-06-19 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_image_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.day'),
        ),
    ]
